#ShadowAntiGrief Configuration File
#Which blocks would you like to be blocked?
Enable-Beacon: true
Enable-Bedrock: true
Enable-Build: true
Enable-Dispenser: true
Enable-Dropper: true
Enable-End: true
Enable-Fire: true
Enable-Ice: true
Enable-Lava: true
Enable-Snow: true
Enable-Spawner: true
Enable-TNT: true
Enable-Water: true
#ModReq?
ModReq-Beacon: true
ModReq-Bedrock: true
ModReq-Build: true
ModReq-Dispenser: true
ModReq-Dropper: true
ModReq-End: true
ModReq-Fire: true
ModReq-Ice: true
ModReq-Lava: true
ModReq-Snow: true
ModReq-Spawner: true
ModReq-TNT: true
ModReq-Water: true
#Eggs?
Enable-Egg-Creeper: true
Enable-Egg-Skeleton: true
Enable-Egg-Spider: true
Enable-Egg-Zombie: true
Enable-Egg-Slime: true
Enable-Egg-Ghast: true
Enable-Egg-ZombiePigman: true
Enable-Egg-Enderman: true
Enable-Egg-CaveSpider: true
Enable-Egg-Silverfish: true
Enable-Egg-Blaze: true
Enable-Egg-MagmaCube: true
Enable-Egg-Witch: true
Enable-Egg-Bat: true
Enable-Egg-Pig: true
Enable-Egg-Sheep: true
Enable-Egg-Cow: true
Enable-Egg-Chicken: true
Enable-Egg-Squid: true
Enable-Egg-Wolf: true
Enable-Egg-Mooshroom: true
Enable-Egg-Ocelot: true
Enable-Egg-Villager: true
#ModReq Eggs?
ModReq-Egg-Creeper: true
ModReq-Egg-Skeleton: true
ModReq-Egg-Spider: true
ModReq-Egg-Zombie: true
ModReq-Egg-Slime: true
ModReq-Egg-Ghast: true
ModReq-Egg-ZombiePigman: true
ModReq-Egg-Enderman: true
ModReq-Egg-CaveSpider: true
ModReq-Egg-Silverfish: true
ModReq-Egg-Blaze: true
ModReq-Egg-MagmaCube: true
ModReq-Egg-Witch: true
ModReq-Egg-Bat: true
ModReq-Egg-Pig: true
ModReq-Egg-Sheep: true
ModReq-Egg-Cow: true
ModReq-Egg-Chicken: true
ModReq-Egg-Squid: true
ModReq-Egg-Wolf: true
ModReq-Egg-Mooshroom: true
ModReq-Egg-Ocelot: true
ModReq-Egg-Villager: true
#Wither Spawn?
Block-Wither-Spawn: true