#ShadowAntiGrief Configuration File
#Which blocks would you like to be blocked?
Enable-Beacon: true
Enable-Bedrock: true
Enable-Build: true
Enable-Dispenser: true
Enable-Dropper: true
Enable-End: true
Enable-Fire: true
Enable-Ice: true
Enable-Lava: true
Enable-Snow: true
Enable-Spawner: true
Enable-TNT: true
Enable-Water: true
#ModReq?
ModReq-Beacon: false
ModReq-Bedrock: false
ModReq-Build: false
ModReq-Dispenser: false
ModReq-Dropper: false
ModReq-End: false
ModReq-Fire: false
ModReq-Ice: false
ModReq-Lava: false
ModReq-Snow: false
ModReq-Spawner: false
ModReq-TNT: false
ModReq-Water: false
#Which eggs would you like to be blocked?
Enable-Egg-Creeper: true
Enable-Egg-Skeleton: true
Enable-Egg-Spider: true
Enable-Egg-Zombie: true
Enable-Egg-Slime: true
Enable-Egg-Ghast: true
Enable-Egg-ZombiePigman: true
Enable-Egg-Enderman: true
Enable-Egg-CaveSpider: true
Enable-Egg-Silverfish: true
Enable-Egg-Blaze: true
Enable-Egg-MagmaCube: true
Enable-Egg-Witch: true
Enable-Egg-Bat: true
Enable-Egg-Pig: true
Enable-Egg-Sheep: true
Enable-Egg-Cow: true
Enable-Egg-Chicken: true
Enable-Egg-Squid: true
Enable-Egg-Wolf: true
Enable-Egg-Mooshroom: true
Enable-Egg-Ocelot: true
Enable-Egg-Villager: true
#ModReq Eggs?
ModReq-Egg-Creeper: false
ModReq-Egg-Skeleton: false
ModReq-Egg-Spider: false
ModReq-Egg-Zombie: false
ModReq-Egg-Slime: false
ModReq-Egg-Ghast: false
ModReq-Egg-ZombiePigman: false
ModReq-Egg-Enderman: false
ModReq-Egg-CaveSpider: false
ModReq-Egg-Silverfish: false
ModReq-Egg-Blaze: false
ModReq-Egg-MagmaCube: false
ModReq-Egg-Witch: false
ModReq-Egg-Bat: false
ModReq-Egg-Pig: false
ModReq-Egg-Sheep: false
ModReq-Egg-Cow: false
ModReq-Egg-Chicken: false
ModReq-Egg-Squid: false
ModReq-Egg-Wolf: false
ModReq-Egg-Mooshroom: false
ModReq-Egg-Ocelot: false
ModReq-Egg-Villager: false
#Do you want to allow Withers to Spawn?
Block-Wither-Spawn: true
#Do you want to block creepers from destroying blocks when they explode?
Creeper-Explosion: true